import base64
from dataclasses import dataclass, field
from typing import Literal, Union
import time


def _now_ms() -> int:
    """Return current Unix timestamp in milliseconds."""
    return int(time.time() * 1000)


@dataclass
class UserInputEvent:
    """
    Event emitted when raw audio data is received from the user.

    This is the entry point of the voice agent pipeline. Audio should be
    in PCM format (16-bit, mono, 16kHz) for optimal processing by the STT stage.
    """

    audio_data: bytes
    type: Literal["user_input"] = "user_input"
    timestamp: int = field(default_factory=_now_ms)

    @classmethod
    def create(cls, audio_data: bytes) -> "UserInputEvent":
        return cls(audio_data=audio_data)


@dataclass
class STTChunkEvent:
    """
    Event emitted when a chunk of text is generated by the STT stage.
    """

    text: str
    type: Literal["stt_chunk"] = "stt_chunk"
    timestamp: int = field(default_factory=_now_ms)

    @classmethod
    def create(cls, text: str) -> "STTChunkEvent":
        return cls(text=text)


@dataclass
class STTOutputEvent:
    """
    Event emitted when the STT stage has finished processing the audio.
    """

    text: str
    type: Literal["stt_output"] = "stt_output"
    timestamp: int = field(default_factory=_now_ms)

    @classmethod
    def create(cls, text: str) -> "STTOutputEvent":
        return cls(text=text)


STT_EVENT = Union[STTChunkEvent, STTOutputEvent]


@dataclass
class AgentChunkEvent:
    """
    Event emitted when a chunk of text is generated by the agent stage.
    """

    text: str
    type: Literal["agent_chunk"] = "agent_chunk"
    timestamp: int = field(default_factory=_now_ms)

    @classmethod
    def create(cls, text: str) -> "AgentChunkEvent":
        return cls(text=text)


@dataclass
class AgentEndEvent:
    """
    Event emitted when the agent has finished generating its response for a turn.

    This signals downstream consumers (like TTS) that no more text is coming
    for this turn and they should flush any buffered content.
    """

    type: Literal["agent_end"] = "agent_end"

    timestamp: int = field(default_factory=_now_ms)

    @classmethod
    def create(cls) -> "AgentEndEvent":
        """Factory method to create an AgentEndEvent event with current timestamp."""
        return cls()


@dataclass
class ToolCallEvent:
    """
    Event emitted when the agent invokes a tool.

    This event provides visibility into the agent's decision-making process,
    showing which tools are being called and with what arguments.
    """

    id: str
    """Unique identifier for this tool invocation."""

    name: str
    """Name of the tool being invoked."""

    args: dict
    """Arguments passed to the tool."""
    type: Literal["tool_call"] = "tool_call"

    timestamp: int = field(default_factory=_now_ms)

    @classmethod
    def create(cls, id: str, name: str, args: dict) -> "ToolCallEvent":
        """Factory method to create a ToolCallEvent event with current timestamp."""
        return cls(type="tool_call", id=id, name=name, args=args, timestamp=_now_ms)


@dataclass
class ToolResultEvent:
    """
    Event emitted when a tool completes execution and returns a result.

    This event contains the output from the tool, allowing tracking of
    the full tool execution lifecycle.
    """

    tool_call_id: str
    """The tool call ID this result corresponds to."""

    name: str
    """Name of the tool that was executed."""

    result: str
    """The result returned by the tool."""
    type: Literal["tool_result"] = "tool_result"

    timestamp: int = field(default_factory=_now_ms)

    @classmethod
    def create(cls, tool_call_id: str, name: str, result: str) -> "ToolResultEvent":
        """Factory method to create a ToolResultEvent event with current timestamp."""
        return cls(
            type="tool_result",
            tool_call_id=tool_call_id,
            name=name,
            result=result,
            timestamp=_now_ms,
        )


AGENT_EVENT = Union[AgentChunkEvent, AgentEndEvent, ToolCallEvent, ToolResultEvent]


@dataclass
class TTSChunkEvent:
    """
    Event emitted when a chunk of audio is generated by the TTS stage.
    """

    audio: bytes
    """
    PCM audio bytes synthesized from the agent's text response.
    Format: 16-bit signed integer, mono channel, 24kHz sample rate.
    Encoded as base64 when serialized to JSON for transmission.
    Can be played immediately as it arrives for low-latency audio output.
    """
    type: Literal["tts_chunk"] = "tts_chunk"
    timestamp: int = field(default_factory=_now_ms)

    @classmethod
    def create(cls, audio: bytes) -> "TTSChunkEvent":
        return cls(audio=audio)


VoiceAgentEvent = Union[UserInputEvent, STT_EVENT, AGENT_EVENT, TTSChunkEvent]


def event_to_dict(event: VoiceAgentEvent) -> dict:
    """Convert a VoiceAgentEvent to a JSON-serializable dictionary."""
    if isinstance(event, UserInputEvent):
        return {"type": event.type, "timestamp": event.timestamp}
    elif isinstance(event, STTChunkEvent):
        return {"type": event.type, "text": event.text, "timestamp": event.timestamp}
    elif isinstance(event, STTOutputEvent):
        return {"type": event.type, "text": event.text, "timestamp": event.timestamp}
    elif isinstance(event, AgentChunkEvent):
        return {"type": event.type, "text": event.text, "timestamp": event.timestamp}
    elif isinstance(event, AgentEndEvent):
        return {"type": event.type, "timestamp": event.timestamp}
    elif isinstance(event, ToolCallEvent):
        return {
            "type": event.type,
            "id": event.id,
            "name": event.name,
            "args": event.args,
            "timestamp": event.timestamp,
        }
    elif isinstance(event, ToolResultEvent):
        return {
            "type": event.type,
            "toolCallId": event.tool_call_id,
            "name": event.name,
            "result": event.result,
            "timestamp": event.timestamp,
        }
    elif isinstance(event, TTSChunkEvent):
        return {
            "type": event.type,
            "audio": base64.b64encode(event.audio).decode("ascii"),
            "timestamp": event.timestamp,
        }
